name: Everfund SDK Build Examples

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build:
    name: Build SDK Examples
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set USE_SOURCE
        run: echo "USE_SOURCE=true" >> $GITHUB_ENV

      - name: Run build examples
        run: pnpm build
